name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/goldielegenie/dqiv-build:latest

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [eur]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare
        run: |
          rm -rf ./extract/eur
          mv /extract/* ./extract
          cp /arm7_bios.bin ./arm7_bios.bin

      - name: Update wibo
        run: |
          curl -fsSL "https://github.com/decompals/wibo/releases/download/1.2.0/wibo-x86_64" -o /usr/local/bin/wibo
          chmod +x /usr/local/bin/wibo
          wibo --version || true

      - name: Compiler check
        run: |
          echo "--- image /mwccarm (old) ---"
          md5sum /mwccarm/2.0/sp1p6/* || true
          echo "--- expected (tools/mwccarm from decomp.aetias.com) ---"
          echo "166be7090f0ba72ac5acdc7811197dc4  mwccarm.exe"
          echo "27e35a31c5635f2d66e79ed7600defab  mwldarm.exe"
          echo "72e119db9ebe77f64142f4e7509166c3  MSL_All-DLL80_x86.dll"

      - name: Build
        run: |
          python3 tools/configure.py -w wibo --no-extract ${{ matrix.version }}
          ninja arm9 report || true
          echo "--- CI SHA1 ---"
          sha1sum dqiv_eur.nds || true
          echo "--- Expected SHA1 ---"
          cat config/eur/dqiv_eur.sha1 || true

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}_report
          path: build/${{ matrix.version }}/report.json
          if-no-files-found: warn

      - name: Upload compiled objects
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}_objects
          path: build/${{ matrix.version }}/src/
          if-no-files-found: warn

      - name: Upload ROM and linked object
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}_rom_and_obj
          path: |
            dqiv_eur.nds
            build/${{ matrix.version }}/arm9.o
          if-no-files-found: warn
